create table if not exists public.professions (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  category_slug text not null,
  category_name_id text not null,
  category_name_en text not null,
  name_id text not null,
  name_en text not null,
  description_id text not null,
  description_en text not null,
  salary_min integer,
  salary_max integer,
  education_id text,
  education_en text,
  skills_id jsonb not null default '[]'::jsonb,
  skills_en jsonb not null default '[]'::jsonb,
  work_environment_id text,
  work_environment_en text,
  career_path_id text,
  career_path_en text,
  prospects text not null,
  work_life_balance smallint,
  image_url text,
  is_featured boolean not null default false,
  matched_mbti jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint professions_salary_range_check check (salary_min is null or salary_max is null or salary_min <= salary_max),
  constraint professions_work_life_balance_check check (work_life_balance is null or work_life_balance between 1 and 5)
);

alter table public.professions enable row level security;

drop policy if exists "Anyone can view published professions" on public.professions;
create policy "Anyone can view published professions"
  on public.professions for select
  using (true);

create index if not exists professions_category_slug_idx on public.professions (category_slug);
create index if not exists professions_featured_idx on public.professions (is_featured) where is_featured = true;
