-- Migration: 0009_majors_schema.sql
-- Description: Create public.majors table with O*NET CIP taxonomy, RIASEC alignments, and RLS policies

-- Drop legacy table structure if it already exists
DROP TABLE IF EXISTS public.majors CASCADE;

CREATE TABLE public.majors (
  id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  cip_code TEXT NOT NULL,
  name_id TEXT NOT NULL,
  name_en TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('Saintek', 'Soshum', 'Seni')),
  description_id TEXT NOT NULL,
  description_en TEXT NOT NULL,
  typical_subjects_id JSONB NOT NULL DEFAULT '[]'::jsonb,
  typical_subjects_en JSONB NOT NULL DEFAULT '[]'::jsonb,
  min_education_level TEXT NOT NULL,
  avg_duration_years NUMERIC(3, 1) NOT NULL DEFAULT 4.0,
  career_prospect TEXT NOT NULL CHECK (career_prospect IN ('High', 'Medium', 'Low')),
  riasec_code TEXT,
  matched_mbti JSONB NOT NULL DEFAULT '[]'::jsonb,
  matched_professions_slugs JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_majors_slug ON public.majors (slug);
CREATE INDEX IF NOT EXISTS idx_majors_category ON public.majors (category);
CREATE INDEX IF NOT EXISTS idx_majors_cip_code ON public.majors (cip_code);
CREATE INDEX IF NOT EXISTS idx_majors_career_prospect ON public.majors (career_prospect);

-- Enable Row Level Security (RLS)
ALTER TABLE public.majors ENABLE ROW LEVEL SECURITY;

-- Public Read Policy: Allow anyone to view catalog majors
DROP POLICY IF EXISTS "Public can view majors" ON public.majors;
CREATE POLICY "Public can view majors"
  ON public.majors
  FOR SELECT
  USING (true);

-- Admin mutation policy (Service role only)
DROP POLICY IF EXISTS "Service role can modify majors" ON public.majors;
CREATE POLICY "Service role can modify majors"
  ON public.majors
  FOR ALL
  USING (auth.role() = 'service_role');

-- Seed initial majors dataset
INSERT INTO public.majors (
  id,
  slug,
  cip_code,
  name_id,
  name_en,
  category,
  description_id,
  description_en,
  typical_subjects_id,
  typical_subjects_en,
  min_education_level,
  avg_duration_years,
  career_prospect,
  riasec_code,
  matched_mbti,
  matched_professions_slugs
) VALUES
(
  'm-teknik-informatika',
  'teknik-informatika',
  '11.0701',
  'Teknik Informatika & Ilmu Komputer',
  'Computer Science & Software Engineering',
  'Saintek',
  'Program studi yang mendalami komputasi algoritmik, rekayasa perangkat lunak skala besar, kecerdasan buatan, dan arsitektur komputasi awan berkinerja tinggi.',
  'Academic field studying algorithmic computation, enterprise software engineering, artificial intelligence, and high-performance cloud architecture.',
  '["Struktur Data & Algoritma","Rekayasa Perangkat Lunak","Arsitektur Komputer","Basis Data Lanjutan","Kecerdasan Buatan & ML"]'::jsonb,
  '["Data Structures & Algorithms","Software Engineering","Computer Architecture","Advanced Databases","Artificial Intelligence & ML"]'::jsonb,
  'S1',
  4,
  'High',
  'IRC',
  '["INTJ","INTP","ENTJ","ISTP"]'::jsonb,
  '["software-engineer","devops-engineer","cloud-solutions-architect","qa-automation-engineer"]'::jsonb
),
(
  'm-sains-data',
  'sains-data',
  '30.7001',
  'Sains Data & Analitika Tingkat Lanjut',
  'Data Science & Advanced Analytics',
  'Saintek',
  'Pendidikan interdisipliner menggabungkan statistik inferensial, machine learning, data mining, dan visualisasi prediktif untuk menyelesaikan masalah bisnis kompleks.',
  'Interdisciplinary study combining inferential statistics, machine learning, data mining, and predictive visualization for complex business problems.',
  '["Statistika Terapan & Probabilitas","Machine Learning & Deep Learning","Big Data Engineering","Data Wrangling & SQL","Visualisasi Data & BI"]'::jsonb,
  '["Applied Statistics & Probability","Machine Learning & Deep Learning","Big Data Engineering","Data Wrangling & SQL","Data Visualization & BI"]'::jsonb,
  'S1',
  4,
  'High',
  'IRC',
  '["INTP","INTJ","ENTP","ISTJ"]'::jsonb,
  '["data-scientist","ai-machine-learning-engineer","database-administrator"]'::jsonb
),
(
  'm-keamanan-siber',
  'keamanan-siber',
  '11.1003',
  'Keamanan Siber & Forensik Digital',
  'Cybersecurity & Digital Forensics',
  'Saintek',
  'Mempelajari pertahanan infrastruktur jaringan, kriptografi modern, ethical hacking, deteksi ancaman siber, dan audit kepatuhan keamanan informasi.',
  'Focuses on network defense, modern cryptography, ethical hacking, threat detection, and information security regulatory compliance.',
  '["Kriptografi & Keamanan Jaringan","Ethical Hacking & Penetration Testing","Forensik Digital","Manajemen Resiko Siber","Keamanan Cloud & OS"]'::jsonb,
  '["Cryptography & Network Security","Ethical Hacking & Penetration Testing","Digital Forensics","Cyber Risk Management","Cloud & OS Security"]'::jsonb,
  'S1',
  4,
  'High',
  'RIC',
  '["INTJ","ISTJ","INTP","ISTP"]'::jsonb,
  '["cybersecurity-specialist","devops-engineer","cloud-solutions-architect"]'::jsonb
),
(
  'm-sistem-informasi',
  'sistem-informasi',
  '11.0401',
  'Sistem Informasi & Manajemen TI',
  'Information Systems & IT Management',
  'Saintek',
  'Menjembatani kapabilitas teknologi komputasi dengan strategi operasional bisnis, tata kelola TI perusahaan, dan manajemen transformasi digital.',
  'Bridges computing technology capabilities with operational business strategy, enterprise IT governance, and digital transformation management.',
  '["Analisis & Perancangan Sistem","Tata Kelola TI (IT Governance)","Arsitektur Enterprise","Manajemen Proyek TI","E-Business & CRM"]'::jsonb,
  '["Systems Analysis & Design","IT Governance","Enterprise Architecture","IT Project Management","E-Business & CRM"]'::jsonb,
  'S1',
  4,
  'High',
  'ECS',
  '["ENTJ","ESTJ","INTJ","ENFJ"]'::jsonb,
  '["product-manager","database-administrator","digital-marketer"]'::jsonb
),
(
  'm-rekayasa-perangkat-lunak',
  'rekayasa-perangkat-lunak',
  '14.0903',
  'Rekayasa Perangkat Lunak (Software Engineering)',
  'Software Engineering & Architecture',
  'Saintek',
  'Fokus mendalam pada metodologi siklus hidup perangkat lunak (SDLC), pengujian otomatis (QA), desain mikrosistem, dan skalabilitas arsitektur.',
  'Deep dive into SDLC methodologies, automated software quality assurance (QA), microservices design, and architectural scalability.',
  '["Clean Code & Design Patterns","Metodologi Agile & Scrum","Automated Testing & QA","DevOps & Pipeline CI/CD","Arsitektur Mikroservis"]'::jsonb,
  '["Clean Code & Design Patterns","Agile & Scrum Methodologies","Automated Testing & QA","DevOps & CI/CD Pipelines","Microservices Architecture"]'::jsonb,
  'S1',
  4,
  'High',
  'IRC',
  '["INTJ","INTP","ISTJ","ENTJ"]'::jsonb,
  '["software-engineer","qa-automation-engineer","mobile-app-developer"]'::jsonb
),
(
  'm-teknologi-game',
  'teknologi-game',
  '11.0804',
  'Teknologi Game & Media Interaktif',
  'Game Development & Interactive Media',
  'Saintek',
  'Mempelajari rekayasa engine game, pemodelan fisika komputasi, gameplay scripting, grafika komputer realtime, dan sistem realitas tertambah (AR/VR).',
  'Studies game engine engineering, physics computation, gameplay scripting, realtime computer graphics, and augmented/virtual reality (AR/VR).',
  '["Fisika & Matematika Game","Pemrograman Game 3D (Unity/Unreal)","Grafika Komputer Real-time","Desain Mekanik Game","VR/AR Development"]'::jsonb,
  '["Game Physics & Math","3D Game Programming (Unity/Unreal)","Real-time Computer Graphics","Game Mechanics Design","VR/AR Development"]'::jsonb,
  'S1',
  4,
  'High',
  'AIR',
  '["INTP","ISTP","ENTP","ENFP"]'::jsonb,
  '["game-designer","animator-3d-artist","software-engineer"]'::jsonb
),
(
  'm-arsitektur',
  'arsitektur',
  '04.0201',
  'Arsitektur & Perancangan Kota',
  'Architecture & Urban Design',
  'Saintek',
  'Perpaduan estetika seni, fungsi spasial, dan teknologi struktur bangunan berkelanjutan dengan pemanfaatan Building Information Modeling (BIM).',
  'Synthesis of artistic aesthetics, spatial functionality, and sustainable structural technology utilizing Building Information Modeling (BIM).',
  '["Studio Perancangan Arsitektur","Teknologi Bangunan & Struktur","Arsitektur Berkelanjutan","BIM & Pemodelan Komputasional","Sejarah & Teori Arsitektur"]'::jsonb,
  '["Architectural Design Studio","Building Technology & Structure","Sustainable Architecture","BIM & Computational Modeling","History & Theory of Architecture"]'::jsonb,
  'S1 + Profesi',
  5,
  'High',
  'AIR',
  '["INTJ","INFJ","ENTP","ISTP"]'::jsonb,
  '["architect","interior-designer"]'::jsonb
),
(
  'm-teknik-sipil',
  'teknik-sipil',
  '14.0801',
  'Teknik Sipil & Infrastruktur',
  'Civil & Infrastructure Engineering',
  'Saintek',
  'Perancangan, kalkulasi kekuatan, konstruksi, dan pemeliharaan infrastruktur strategis seperti jembatan, jalan tol, pelabuhan, gedung bertingkat, dan bendungan.',
  'Design, structural analysis, construction, and maintenance of strategic civil infrastructures including bridges, highways, ports, high-rises, and dams.',
  '["Mekanika Tanah & Geoteknik","Analisis Struktur Beton & Baja","Teknik Transportasi","Hidrologi & Sumber Daya Air","Manajemen Konstruksi"]'::jsonb,
  '["Soil Mechanics & Geotechnics","Concrete & Steel Structural Analysis","Transportation Engineering","Hydrology & Water Resources","Construction Management"]'::jsonb,
  'S1',
  4,
  'High',
  'RIC',
  '["ISTJ","ESTJ","INTJ","ISTP"]'::jsonb,
  '["civil-engineer","architect"]'::jsonb
),
(
  'm-teknik-mesin',
  'teknik-mesin',
  '14.1901',
  'Teknik Mesin & Manufaktur',
  'Mechanical & Manufacturing Engineering',
  'Saintek',
  'Penerapan prinsip termodinamika, mekanika fluida, kinematika material, dan sistem otomasi manufaktur dalam perancangan mesin industri canggih.',
  'Application of thermodynamics, fluid dynamics, material kinematics, and manufacturing automation in designing advanced industrial machinery.',
  '["Termodinamika & Perpindahan Panas","Mekanika Fluida","Elemen Mesin & CAD/CAM","Kinematika & Dinamika","Otomasi & Robotika Industri"]'::jsonb,
  '["Thermodynamics & Heat Transfer","Fluid Mechanics","Machine Elements & CAD/CAM","Kinematics & Dynamics","Industrial Automation & Robotics"]'::jsonb,
  'S1',
  4,
  'High',
  'RIE',
  '["ISTP","INTJ","INTP","ESTJ"]'::jsonb,
  '["mechanical-engineer","civil-engineer"]'::jsonb
),
(
  'm-teknik-elektro',
  'teknik-elektro',
  '14.1001',
  'Teknik Elektro & Sistem Tenaga',
  'Electrical & Power Systems Engineering',
  'Saintek',
  'Mempelajari transmisi energi listrik tegangan tinggi, sistem kendali otomasi industri, mikroelektronika semikonduktor, dan sistem tenaga baru terbarukan.',
  'Focuses on high-voltage power transmission, industrial control automation, semiconductor microelectronics, and renewable energy systems.',
  '["Rangkaian Listrik & Elektromagnetika","Sistem Tenaga Listrik","Sistem Kendali & Instrumentasi","Elektronika Daya","Energi Terbarukan"]'::jsonb,
  '["Electric Circuits & Electromagnetics","Electric Power Systems","Control Systems & Instrumentation","Power Electronics","Renewable Energy"]'::jsonb,
  'S1',
  4,
  'High',
  'RIE',
  '["INTJ","INTP","ISTJ","ISTP"]'::jsonb,
  '["electrical-engineer","mechanical-engineer"]'::jsonb
),
(
  'm-teknik-biomedis',
  'teknik-biomedis',
  '14.0501',
  'Teknik Biomedis (Biomedical Engineering)',
  'Biomedical Engineering & Bio-Instrumentation',
  'Saintek',
  'Integrasi ilmu rekayasa teknik dengan biologi medis untuk merancang perangkat diagnostik, implan prostetik, dan instrumentasi rumah sakit modern.',
  'Integrates engineering sciences with medical biology to develop diagnostic equipment, prosthetic implants, and modern healthcare instrumentation.',
  '["Fisiologi Komputasi","Biomaterial & Implan","Instrumentasi Medis","Pengolahan Sinyal Biomedis","Rekayasa Jaringan"]'::jsonb,
  '["Computational Physiology","Biomaterials & Implants","Medical Instrumentation","Biomedical Signal Processing","Tissue Engineering"]'::jsonb,
  'S1',
  4,
  'High',
  'IRC',
  '["INTJ","INTP","INFJ","ISTP"]'::jsonb,
  '["research-scientist","radiologic-technologist"]'::jsonb
),
(
  'm-teknik-industri',
  'teknik-industri',
  '14.3501',
  'Teknik Industri & Manajemen Operasi',
  'Industrial Engineering & Operations Research',
  'Saintek',
  'Optimalisasi sistem terintegrasi yang melibatkan manusia, material, informasi, peralatan, dan energi untuk efisiensi produksi dan rantai pasok global.',
  'Optimization of integrated systems involving people, materials, information, equipment, and energy for lean manufacturing and supply chain efficiency.',
  '["Riset Operasional & Optimasi","Ergonomi & Perancangan Sistem Kerja","Manajemen Rantai Pasok (SCM)","Pengendalian Kualitas (Six Sigma)","Simulasi Sistem Industri"]'::jsonb,
  '["Operations Research & Optimization","Ergonomics & Work System Design","Supply Chain Management (SCM)","Quality Control (Six Sigma)","Industrial System Simulation"]'::jsonb,
  'S1',
  4,
  'High',
  'EIR',
  '["ENTJ","ESTJ","INTJ","ISTJ"]'::jsonb,
  '["product-manager","business-development-manager"]'::jsonb
),
(
  'm-teknik-lingkungan',
  'teknik-lingkungan',
  '14.1401',
  'Teknik Lingkungan & Rekayasa Air',
  'Environmental Engineering & Water Resources',
  'Saintek',
  'Pengembangan solusi teknis untuk perlindungan lingkungan hidup, pengolahan air bersih dan limbah, mitigasi polusi udara, dan audit lingkungan.',
  'Development of engineering solutions for ecological conservation, clean water & wastewater treatment, air pollution mitigation, and environmental auditing.',
  '["Pengolahan Air Minum & Air Buangan","Pengendalian Pencemaran Udara","Pengelolaan Sampah Terpadu","AMDAL & Audit Lingkungan","Kimia Lingkungan"]'::jsonb,
  '["Water & Wastewater Treatment","Air Pollution Control","Integrated Solid Waste Management","EIA & Environmental Audit","Environmental Chemistry"]'::jsonb,
  'S1',
  4,
  'High',
  'RIC',
  '["INFJ","INTJ","ISTJ","INFP"]'::jsonb,
  '["research-scientist","civil-engineer"]'::jsonb
),
(
  'm-kedokteran',
  'kedokteran',
  '51.1201',
  'Pendidikan Kedokteran & Profesi Dokter',
  'Medicine & Clinical Healthcare',
  'Saintek',
  'Pendidikan komprehensif sains biomedis, patofisiologi organ, farmakoterapi, diagnosa klinis, dan ketrampilan prosedur medis untuk menyembuhkan pasien.',
  'Comprehensive education in biomedical sciences, pathophysiology, pharmacotherapy, clinical diagnosis, and procedural medical skills to heal patients.',
  '["Anatomi Klinis & Fisiologi","Patologi Anatomi & Klinik","Farmakologi Kedokteran","Kepaniteraan Klinik (Koas)","Etika & Hukum Kedokteran"]'::jsonb,
  '["Clinical Anatomy & Physiology","Anatomical & Clinical Pathology","Medical Pharmacology","Clinical Clerkship","Medical Ethics & Jurisprudence"]'::jsonb,
  'S1 + Profesi',
  5.5,
  'High',
  'ISR',
  '["ISTJ","ISFJ","INTJ","INFJ"]'::jsonb,
  '["dokter-umum","pediatrician","psychiatrist"]'::jsonb
),
(
  'm-kedokteran-gigi',
  'kedokteran-gigi',
  '51.0401',
  'Kedokteran Gigi & Bedah Mulut',
  'Dentistry & Oral Health Sciences',
  'Saintek',
  'Studi preventif, kuratif, dan rehabilitatif untuk kesehatan gigi, rahang, rongga mulut, serta prosedur bedah mulut dan estetika ortodonsia.',
  'Preventive, curative, and restorative study for dental health, jaws, oral cavity, oral surgery, and aesthetic orthodontics.',
  '["Biologi Oral & Morfologi Gigi","Konservasi Gigi & Endodonsia","Bedah Mulut & Maksilofasial","Ortodonsia & Prostodonsia","Radiologi Kedokteran Gigi"]'::jsonb,
  '["Oral Biology & Dental Morphology","Operative Dentistry & Endodontics","Oral & Maxillofacial Surgery","Orthodontics & Prosthodontics","Dental Radiology"]'::jsonb,
  'S1 + Profesi',
  5,
  'High',
  'ISR',
  '["ISFJ","ISTJ","ESFJ","ESTJ"]'::jsonb,
  '["dokter-gigi"]'::jsonb
),
(
  'm-farmasi',
  'farmasi',
  '51.2001',
  'Farmasi Klinis & Sains Obat',
  'Pharmacy & Pharmaceutical Sciences',
  'Saintek',
  'Mempelajari sintesis senyawa obat, formulasi sediaan farmasi, uji klinis, farmakokinetika, dan dispensing obat dalam sistem pelayanan kesehatan.',
  'Studies pharmaceutical drug synthesis, dosage formulation, clinical trials, pharmacokinetics, and healthcare therapeutic dispensing.',
  '["Kimia Farmasi & Sintesis Obat","Farmakologi & Toksikologi","Teknologi Formulasi Sediaan","Farmasi Klinis & Komunitas","Biofarmasetika"]'::jsonb,
  '["Pharmaceutical Chemistry","Pharmacology & Toxicology","Formulation Technology","Clinical & Community Pharmacy","Biopharmaceutics"]'::jsonb,
  'S1 + Profesi',
  5,
  'High',
  'ICR',
  '["ISTJ","INTJ","ISFJ","INTP"]'::jsonb,
  '["apoteker","research-scientist"]'::jsonb
),
(
  'm-ilmu-keperawatan',
  'ilmu-keperawatan',
  '51.3801',
  'Ilmu Keperawatan (Nursing)',
  'Nursing & Patient Care Management',
  'Saintek',
  'Pelayanan holistik bio-psiko-sosio-spiritual bagi pasien, manajemen keperawatan kritis, perawatan pascaoperasi, dan promotif kesehatan masyarakat.',
  'Holistic patient care, critical care nursing management, post-operative rehabilitation, and community health promotion.',
  '["Keperawatan Medikal Bedah","Keperawatan Kritis & Gawat Darurat","Keperawatan Anak & Maternitas","Farmakologi Keperawatan","Manajemen Patient Safety"]'::jsonb,
  '["Medical-Surgical Nursing","Critical & Emergency Care","Pediatric & Maternal Nursing","Nursing Pharmacology","Patient Safety Management"]'::jsonb,
  'S1 + Profesi',
  5,
  'High',
  'SIC',
  '["ISFJ","ESFJ","INFJ","ENFJ"]'::jsonb,
  '["perawat","nurse-midwife"]'::jsonb
),
(
  'm-ilmu-gizi',
  'ilmu-gizi',
  '51.3101',
  'Ilmu Gizi & Dietetika Klinis',
  'Nutritional Sciences & Clinical Dietetics',
  'Saintek',
  'Korelasi zat gizi pangan dengan metabolisme manusia, terapi dietetik penyakit degeneratif, dan manajemen gizi institusi perhotelan/rumah sakit.',
  'Correlation of food nutrients with human metabolism, therapeutic medical nutrition for chronic illnesses, and institutional catering management.',
  '["Biokimia Gizi Manusia","Dietetika Penyakit Infeksi & Degeneratif","Penilaian Status Gizi","Manajemen Pelayanan Makanan","Gizi Olahraga & Kebugaran"]'::jsonb,
  '["Human Nutritional Biochemistry","Clinical Dietetics","Nutritional Assessment","Food Service Management","Sports & Fitness Nutrition"]'::jsonb,
  'S1',
  4,
  'High',
  'ISR',
  '["ISFJ","INFJ","ESFJ","ISTJ"]'::jsonb,
  '["clinical-dietitian"]'::jsonb
),
(
  'm-fisioterapi',
  'fisioterapi',
  '51.2308',
  'Fisioterapi & Rehabilitasi Fisik',
  'Physical Therapy & Movement Rehabilitation',
  'Saintek',
  'Pengembangan, pemeliharaan, dan pemulihan gerak fungsional tubuh akibat cedera olahraga, trauma stroke, maupun kelainan neuromuskular.',
  'Development, preservation, and restoration of physical mobility caused by sports injuries, stroke trauma, or neuromuscular disorders.',
  '["Anatomi Muskuloskeletal & Kinesiologi","Fisioterapi Neuromuskular","Fisioterapi Olahraga & Kebugaran","Elektroterapi & Manual Therapy","Biomekanik Gerak Tubuh"]'::jsonb,
  '["Musculoskeletal Anatomy & Kinesiology","Neuromuscular Physical Therapy","Sports Physical Therapy","Electrotherapy & Manual Therapy","Body Biomechanics"]'::jsonb,
  'D4 / S1',
  4,
  'High',
  'SRE',
  '["ISFP","ESFP","ISFJ","ISTP"]'::jsonb,
  '["fisioterapis"]'::jsonb
),
(
  'm-teknologi-laboratorium-medik',
  'teknologi-laboratorium-medik',
  '51.1005',
  'Teknologi Laboratorium Medik (Analis Kesehatan)',
  'Medical Laboratory Technology',
  'Saintek',
  'Pemeriksaan spesimen biologis (darah, jaringan, cairan tubuh) menggunakan teknik hematologi, serologi, dan biologi molekuler untuk menegakkan diagnosis.',
  'Testing biological specimens (blood, tissue, body fluids) using hematology, serology, and molecular diagnostics to validate clinical treatments.',
  '["Hematologi & Koagulasi","Kimia Klinik Lanjutan","Imunologi & Serologi","Mikrobiologi Medis","Biologi Molekuler Diagnostik"]'::jsonb,
  '["Hematology & Coagulation","Advanced Clinical Chemistry","Immunology & Serology","Medical Microbiology","Diagnostic Molecular Biology"]'::jsonb,
  'D4 / S1',
  4,
  'Medium',
  'IRC',
  '["ISTJ","ISFJ","INTP","ISTP"]'::jsonb,
  '["medical-lab-technologist","research-scientist"]'::jsonb
),
(
  'm-radiologi-medis',
  'radiologi-medis',
  '51.0911',
  'Radiologi & Teknik Pencitraan Medis',
  'Radiologic Technology & Medical Imaging',
  'Saintek',
  'Pengoperasian modalitas pencitraan canggih seperti X-Ray, CT-Scan, MRI, dan Kedokteran Nuklir dengan kalkulasi keselamatan radiasi yang ketat.',
  'Operation of advanced diagnostic imaging modalities including X-Ray, CT-Scan, MRI, and Nuclear Medicine under strict radiation safety guidelines.',
  '["Fisika Radiasi & Proteksi Radiasi","Teknik Radiografi Kontras & Non-Kontras","Prosedur CT-Scan & MRI","Anatomi Radiologis","Kendali Mutu Peralatan Radiasi"]'::jsonb,
  '["Radiation Physics & Protection","Contrast Radiography","CT-Scan & MRI Procedures","Radiological Anatomy","Quality Assurance in Radiography"]'::jsonb,
  'D4 / S1',
  4,
  'High',
  'RIC',
  '["ISTJ","ISTP","ISFJ","INTJ"]'::jsonb,
  '["radiologic-technologist"]'::jsonb
),
(
  'm-manajemen-bisnis',
  'manajemen-bisnis',
  '52.0201',
  'Manajemen Bisnis & Kewirausahaan',
  'Business Administration & Entrepreneurship',
  'Soshum',
  'Pengelolaan strategi organisasi, alokasi sumber daya perusahaan, pengembangan produk baru, dan kepemimpinan bisnis di era ekonomi global.',
  'Managing organizational strategy, enterprise resource allocation, product innovation, and business leadership in the global digital economy.',
  '["Manajemen Strategik","Perilaku Organisasi","Manajemen Operasi & Rantai Pasok","Inovasi & Model Bisnis Digital","Kepemimpinan Perusahaan"]'::jsonb,
  '["Strategic Management","Organizational Behavior","Operations & Supply Chain Management","Digital Business Innovation","Corporate Leadership"]'::jsonb,
  'S1',
  4,
  'High',
  'ECS',
  '["ENTJ","ESTJ","ENFJ","ENTP"]'::jsonb,
  '["business-development-manager","product-manager","brand-manager"]'::jsonb
),
(
  'm-akuntansi',
  'akuntansi',
  '52.0301',
  'Akuntansi & Tata Kelola Keuangan',
  'Accounting & Auditing Standards',
  'Soshum',
  'Penyusunan laporan keuangan standar PSAK/IFRS, audit kepatuhan eksternal, akuntansi manajemen biaya, dan perencanaan strategi perpajakan.',
  'Financial statement preparation under PSAK/IFRS, independent auditing, cost management accounting, and strategic corporate taxation planning.',
  '["Akuntansi Keuangan Menengah & Lanjutan","Pengauditan & Assurance (Audit)","Akuntansi Manajemen & Biaya","Hukum Perpajakan Perusahaan","Sistem Informasi Akuntansi"]'::jsonb,
  '["Intermediate & Advanced Financial Accounting","Auditing & Assurance","Managerial & Cost Accounting","Corporate Taxation Law","Accounting Information Systems"]'::jsonb,
  'S1',
  4,
  'High',
  'CEI',
  '["ISTJ","ESTJ","INTJ","ISFJ"]'::jsonb,
  '["public-accountant","financial-analyst"]'::jsonb
),
(
  'm-keuangan-investasi',
  'keuangan-investasi',
  '52.0801',
  'Keuangan Perbankan & Manajemen Investasi',
  'Finance & Investment Management',
  'Soshum',
  'Analisis pasar modal, valuasi sekuritas, manajemen portofolio aset, rekayasa finansial, dan mitigasi resiko investasi korporasi global.',
  'Capital market analysis, securities valuation, asset portfolio management, financial engineering, and corporate investment risk mitigation.',
  '["Analisis Laporan Keuangan","Pasar Modal & Instrumen Derivatif","Manajemen Portofolio & Investasi","Keuangan Korporasi Lanjutan","Fintech & Algorithmic Trading"]'::jsonb,
  '["Financial Statement Analysis","Capital Markets & Derivatives","Portfolio & Investment Management","Advanced Corporate Finance","Fintech & Algorithmic Trading"]'::jsonb,
  'S1',
  4,
  'High',
  'ECI',
  '["ENTJ","INTJ","ESTJ","INTP"]'::jsonb,
  '["financial-analyst","business-development-manager"]'::jsonb
),
(
  'm-pemasaran-digital',
  'pemasaran-digital',
  '52.1401',
  'Pemasaran & Strategi Merek Digital',
  'Marketing Management & Digital Strategy',
  'Soshum',
  'Mempelajari segmentasi pasar, psikologi konsumen, strategi penetapan harga, retensi pelanggan, dan kampanye digital performance marketing.',
  'Studies market segmentation, consumer psychology, pricing strategies, customer retention, and digital performance marketing campaigns.',
  '["Perilaku Konsumen Modern","Digital Marketing Analytics & SEO","Manajemen Merek (Brand Management)","Riset Pasar & Analisis Tren","Komunikasi Pemasaran Terpadu"]'::jsonb,
  '["Consumer Behavior","Digital Marketing Analytics & SEO","Brand Management","Market Research & Trends","Integrated Marketing Communications"]'::jsonb,
  'S1',
  4,
  'High',
  'EAS',
  '["ENFP","ENTP","ESFP","ENFJ"]'::jsonb,
  '["digital-marketer","brand-manager","seo-specialist","social-media-manager"]'::jsonb
),
(
  'm-manajemen-sdm',
  'manajemen-sdm',
  '52.1001',
  'Manajemen Sumber Daya Manusia (SDM)',
  'Human Resources Management',
  'Soshum',
  'Fokus pada rekrutmen talenta strategis, manajemen kinerja karyawan, kompensasi & benefit, pelatihan talenta, dan hukum ketenagakerjaan.',
  'Focuses on strategic talent acquisition, performance appraisals, compensation & benefits, employee development, and labor laws.',
  '["Perencanaan & Rekrutmen Talenta","Kompensasi & Manajemen Kinerja","Pelatihan & Pengembangan Organisasi","Hukum Ketenagakerjaan & Hubungan Industrial","HR Analytics"]'::jsonb,
  '["Talent Planning & Recruitment","Compensation & Performance Management","Training & Organizational Development","Labor Law & Industrial Relations","HR Analytics"]'::jsonb,
  'S1',
  4,
  'High',
  'SEC',
  '["ENFJ","ESFJ","INFJ","ENTJ"]'::jsonb,
  '["human-resources-manager","career-counselor"]'::jsonb
),
(
  'm-psikologi',
  'psikologi',
  '42.0101',
  'Psikologi & Perilaku Manusia',
  'Psychology & Behavioral Sciences',
  'Soshum',
  'Studi ilmiah mengenai proses kognitif, dinamika emosi, kepribadian individu, asesmen psikometri, dan intervensi konseling psikologis.',
  'Scientific study of cognitive processes, emotional dynamics, individual personality, psychometric assessments, and psychological counseling interventions.',
  '["Psikologi Perkembangan","Psikodiagnostika & Asesmen","Psikologi Klinis & Konseling","Psikologi Industri & Organisasi (PIO)","Metodologi Penelitian Psikologi"]'::jsonb,
  '["Developmental Psychology","Psychodiagnostics & Assessment","Clinical & Counseling Psychology","Industrial & Organizational Psychology","Psychological Research Methods"]'::jsonb,
  'S1',
  4,
  'High',
  'SIA',
  '["INFJ","INFP","ENFJ","ENFP"]'::jsonb,
  '["psikolog-klinis","career-counselor","human-resources-manager"]'::jsonb
),
(
  'm-hukum',
  'hukum',
  '22.0101',
  'Ilmu Hukum & Advokasi Korporat',
  'Law & Corporate Jurisprudence',
  'Soshum',
  'Penguasaan tata hukum konstitusi, hukum perdata bisnis, litigasi peradilan, penyusunan kontrak korporasi, dan perlindungan hak asasi manusia.',
  'Mastery of constitutional law, commercial civil law, court litigation, corporate contract drafting, and human rights jurisprudence.',
  '["Hukum Perdata & Bisnis","Hukum Pidana & Acara Pidana","Hukum Tata Negara & Administrasi","Legal Drafting & Penyusunan Kontrak","Hukum Internasional & Perdagangan"]'::jsonb,
  '["Civil & Commercial Law","Criminal Law & Procedure","Constitutional & Administrative Law","Legal Contract Drafting","International & Trade Law"]'::jsonb,
  'S1',
  4,
  'High',
  'ESI',
  '["ENTJ","INTJ","ESTJ","INFJ"]'::jsonb,
  '["public-relations-specialist","business-development-manager"]'::jsonb
),
(
  'm-ilmu-komunikasi',
  'ilmu-komunikasi',
  '09.0101',
  'Ilmu Komunikasi & Media Massa',
  'Communication Studies & Mass Media',
  'Soshum',
  'Mempelajari transmisi pesan verbal dan visual, komunikasi massa, jurnalisme investigatif, produksi konten penyiaran, dan literasi media digital.',
  'Studies verbal and visual messaging, mass communications, investigative journalism, broadcast production, and digital media literacy.',
  '["Teori Komunikasi Kontemporer","Jurnalistik Multimedia","Produksi Media Siar & Podcast","Komunikasi Antarpribadi","Etika & Regulasi Media"]'::jsonb,
  '["Contemporary Communication Theory","Multimedia Journalism","Broadcast & Podcast Production","Interpersonal Communication","Media Ethics & Regulation"]'::jsonb,
  'S1',
  4,
  'High',
  'ASE',
  '["ENFP","ENFJ","ENTP","ESFP"]'::jsonb,
  '["social-media-manager","copywriter","public-relations-specialist"]'::jsonb
),
(
  'm-hubungan-masyarakat',
  'hubungan-masyarakat',
  '09.0902',
  'Hubungan Masyarakat (Public Relations)',
  'Public Relations & Corporate Reputation',
  'Soshum',
  'Manajemen reputasi institusi, penanganan krisis media, relasi pers, strategi CSR berkelanjutan, dan komunikasi pemangku kepentingan.',
  'Institutional reputation management, crisis communication, press relations, sustainable CSR strategy, and stakeholder alignment.',
  '["Manajemen Krisis & Reputasi","Strategi Public Relations","Penulisan PR & Rilis Media","Protokoler & Manajemen Event","Media Relations & Konferensi"]'::jsonb,
  '["Crisis & Reputation Management","PR Strategic Management","PR Writing & Press Releases","Protocol & Event Management","Media Relations"]'::jsonb,
  'S1',
  4,
  'High',
  'EAS',
  '["ENFJ","ESFJ","ENTJ","ENFP"]'::jsonb,
  '["public-relations-specialist","brand-manager"]'::jsonb
),
(
  'm-hubungan-internasional',
  'hubungan-internasional',
  '45.0901',
  'Hubungan Internasional & Diplomasi',
  'International Relations & Global Diplomacy',
  'Soshum',
  'Analisis geopolitik global, diplomasi bilateral dan multilateral, ekonomi politik internasional, serta resolusi konflik lintas batas negara.',
  'Analysis of global geopolitics, bilateral and multilateral diplomacy, international political economy, and cross-border conflict resolution.',
  '["Teori Hubungan Internasional","Diplomasi & Negosiasi Global","Organisasi Internasional & PBB","Ekonomi Politik Internasional","Hukum & Keamanan Global"]'::jsonb,
  '["International Relations Theory","Global Diplomacy & Negotiation","International Organizations & UN","International Political Economy","Global Law & Security"]'::jsonb,
  'S1',
  4,
  'High',
  'ASE',
  '["ENTJ","ENFJ","INTJ","ENTP"]'::jsonb,
  '["public-relations-specialist","research-scientist"]'::jsonb
),
(
  'm-pendidikan-guru-sekolah-menengah',
  'pendidikan-guru-sekolah-menengah',
  '13.1205',
  'Pendidikan Guru & Pedagogi Menengah',
  'Secondary Teacher Education & Pedagogy',
  'Soshum',
  'Pengembangan metodologi pengajaran berbasis kompetensi, manajemen kelas kondusif, asesmen hasil belajar, dan pemanfaatan media instruksional interaktif.',
  'Development of competence-based teaching methodologies, classroom management, learning assessments, and interactive educational media.',
  '["Strategi Pembelajaran Efektif","Pengembangan Kurikulum Merdeka","Evaluasi & Asesmen Pembelajaran","Psikologi Pendidikan Anak","Teknologi Media Pembelajaran"]'::jsonb,
  '["Effective Teaching Strategies","Curriculum Development","Learning Evaluation & Assessment","Educational Psychology","Educational Technology Media"]'::jsonb,
  'S1 + PPG',
  5,
  'Medium',
  'SAE',
  '["ENFJ","ESFJ","INFJ","ISFJ"]'::jsonb,
  '["guru-sekolah-menengah","instructional-designer"]'::jsonb
),
(
  'm-teknologi-pendidikan',
  'teknologi-pendidikan',
  '13.0301',
  'Teknologi Pendidikan & Desain Instruksional',
  'Educational Technology & Instructional Design',
  'Soshum',
  'Merancang kurikulum e-learning modern, modul pelatihan korporat, arsitektur LMS, dan pedagogi interaktif berbasis multimedia.',
  'Designing modern e-learning curricula, corporate training frameworks, LMS architectures, and interactive multimedia pedagogy.',
  '["Desain Instruksional (ADDIE Framework)","Pengembangan Konten E-Learning","Arsitektur Learning Management System (LMS)","Evaluasi Program Pelatihan","Gamifikasi Pembelajaran"]'::jsonb,
  '["Instructional Design (ADDIE Framework)","E-Learning Content Development","LMS Architecture","Training Program Evaluation","Gamification in Learning"]'::jsonb,
  'S1',
  4,
  'High',
  'ASI',
  '["INFJ","INTJ","ENFP","INFP"]'::jsonb,
  '["instructional-designer","dosen-universitas"]'::jsonb
),
(
  'm-bimbingan-konseling',
  'bimbingan-konseling',
  '13.1101',
  'Bimbingan & Konseling Karir',
  'Counselor Education & Guidance Services',
  'Soshum',
  'Penyelenggaraan layanan bimbingan karir, pemahaman bakat dan minat remaja, konseling akademik, serta penanganan masalah psikososial sekolah.',
  'Providing career guidance, adolescent aptitude assessment, academic counseling, and school psychosocial conflict resolution.',
  '["Teknik & Praktik Konseling Individual","Bimbingan Karir & Perencanaan Masa Depan","Asesmen Psikologis Non-Tes","Konseling Kelompok","Kesehatan Mental Remaja"]'::jsonb,
  '["Individual Counseling Techniques","Career Guidance & Future Planning","Non-Test Psychological Assessment","Group Counseling","Adolescent Mental Health"]'::jsonb,
  'S1 + Profesi',
  5,
  'High',
  'SEC',
  '["ENFJ","INFJ","ENFP","ISFJ"]'::jsonb,
  '["career-counselor","psikolog-klinis"]'::jsonb
),
(
  'm-pendidikan-anak-usia-dini',
  'pendidikan-anak-usia-dini',
  '13.1210',
  'Pendidikan Guru PAUD & Tumbuh Kembang',
  'Early Childhood Education & Child Development',
  'Soshum',
  'Metodologi stimulasi sensori motorik, perkembangan bahasa, kecerdasan majemuk, dan pembelajaran eksploratif berbasis bermain untuk balita.',
  'Methodologies for sensory-motor stimulation, language acquisition, multiple intelligences, and play-based explorative early childhood learning.',
  '["Tumbuh Kembang Anak Usia Dini","Pendidikan Berbasis Bermain (Play-based)","Nutrisi & Kesehatan Balita","Media Pembelajaran Sensori","Manajemen Kelas Prasekolah"]'::jsonb,
  '["Early Child Growth & Development","Play-Based Learning Pedagogy","Toddler Nutrition & Health","Sensory Learning Media","Preschool Management"]'::jsonb,
  'S1',
  4,
  'Medium',
  'SAE',
  '["ESFJ","ENFJ","ISFJ","ENFP"]'::jsonb,
  '["kindergarten-teacher"]'::jsonb
),
(
  'm-pendidikan-luar-biasa',
  'pendidikan-luar-biasa',
  '13.1001',
  'Pendidikan Khusus & Luar Biasa (Inklusi)',
  'Special Education & Inclusive Teaching',
  'Soshum',
  'Penyusunan Program Pembelajaran Individual (PPI), braille, bahasa isyarat, dan intervensi edukatif khusus untuk anak berkebutuhan khusus.',
  'Individualized Education Programs (IEP), braille, sign language, and adaptive educational interventions for students with special needs.',
  '["Ortopedagogik Umum","Bahasa Isyarat & Huruf Braille","Desain Program Pembelajaran Individual (PPI)","Modifikasi Perilaku & Sensori","Pendidikan Inklusif Modern"]'::jsonb,
  '["General Orthopedagogy","Sign Language & Braille","Individualized Education Program (IEP)","Behavior & Sensory Modification","Modern Inclusive Education"]'::jsonb,
  'S1',
  4,
  'Medium',
  'SIC',
  '["INFJ","ISFJ","ENFJ","INFP"]'::jsonb,
  '["special-education-teacher"]'::jsonb
),
(
  'm-desain-komunikasi-visual',
  'desain-komunikasi-visual',
  '50.0409',
  'Desain Komunikasi Visual (DKV)',
  'Visual Communication Design (Graphic Design)',
  'Seni',
  'Penciptaan identitas visual merek, tipografi eksperimental, ilustrasi digital, desain kemasan, dan komunikasi grafis lintas media cetak dan layar.',
  'Creation of brand visual identities, experimental typography, digital illustration, packaging design, and cross-media graphic communications.',
  '["Tipografi & Nirmana","Desain Identitas Visual (Branding)","Ilustrasi Digital & Vektor","Desain Kemasan & Promosi","Desain Pengalaman Grafis"]'::jsonb,
  '["Typography & Color Form Principles","Visual Identity & Branding","Digital Vector Illustration","Packaging & Promotional Design","Graphic Experience Design"]'::jsonb,
  'S1',
  4,
  'High',
  'AES',
  '["INFP","ISFP","ENFP","INFJ"]'::jsonb,
  '["graphic-designer","ui-ux-designer","motion-graphic-designer"]'::jsonb
),
(
  'm-desain-produk',
  'desain-produk',
  '50.0404',
  'Desain Produk Industri & Ergonomi',
  'Industrial & Product Design',
  'Seni',
  'Perancangan produk fisik inovatif, alat elektronik konsumen, furnitur ergonomis, pemodelan 3D CAD, dan prototyping cepat berorientasi pengguna.',
  'Design of innovative consumer physical goods, ergonomics furniture, 3D CAD modeling, and user-centric rapid product prototyping.',
  '["Ergonomi & Desain Produk Fisik","Studio Desain Produk","Pemodelan 3D CAD & Rendering","Material & Proses Manufaktur","Rapid Prototyping & 3D Printing"]'::jsonb,
  '["Ergonomics & Physical Product Design","Product Design Studio","3D CAD Modeling & Rendering","Materials & Manufacturing Processes","Rapid Prototyping & 3D Printing"]'::jsonb,
  'S1',
  4,
  'High',
  'AIR',
  '["INTJ","ENTP","ISTP","ISFP"]'::jsonb,
  '["ui-ux-designer","interior-designer"]'::jsonb
),
(
  'm-desain-interior',
  'desain-interior',
  '50.0408',
  'Desain Interior & Tata Ruang',
  'Interior Architecture & Spatial Design',
  'Seni',
  'Perancangan atmosfer ruang dalam bangunan, tata pencahayaan (lighting), pemilihan material tekstur, akustik ruang, dan furnitur kustom.',
  'Design of indoor spatial ambiance, architectural lighting, material finishes, room acoustics, and bespoke built-in furniture.',
  '["Studio Perancangan Ruang Hunian & Komersial","Tata Cahaya & Akustik Ruang","Material Finishing & Furnitur","Gambar Kerja & Estimasi Biaya (RAB)","Rendering 3D Realistis"]'::jsonb,
  '["Residential & Commercial Interior Studio","Lighting & Spatial Acoustics","Finishing Materials & Furniture","Construction Drawings & BOQ","Realistic 3D Rendering"]'::jsonb,
  'S1',
  4,
  'High',
  'AES',
  '["ISFP","INFJ","INTJ","ESFP"]'::jsonb,
  '["interior-designer","architect"]'::jsonb
),
(
  'm-animasi-dan-efek-visual',
  'animasi-dan-efek-visual',
  '50.0102',
  'Animasi 3D & Efek Visual (VFX)',
  'Animation, 3D Arts & Visual Effects (VFX)',
  'Seni',
  'Pembuatan karakter 3D bertekstur, rigging gerak, 12 prinsip animasi, simulasi partikel visual efek, dan sinematografi digital untuk film dan game.',
  '3D character sculpting, motion rigging, 12 animation principles, VFX particle simulations, and digital cinematography for films and games.',
  '["12 Prinsip Dasar Animasi","Modeling 3D & Digital Sculpting","Rigging Karakter & Siklus Jalan","Lighting, Texturing & Shading","Compositing & Visual Effects (VFX)"]'::jsonb,
  '["12 Principles of Animation","3D Modeling & Digital Sculpting","Character Rigging & Walk Cycles","Lighting, Texturing & Shading","Compositing & VFX"]'::jsonb,
  'S1 / D4',
  4,
  'High',
  'ARI',
  '["INFP","ISFP","INTP","ISTP"]'::jsonb,
  '["animator-3d-artist","motion-graphic-designer","video-editor"]'::jsonb
),
(
  'm-film-dan-televisi',
  'film-dan-televisi',
  '50.0602',
  'Film, Sinematografi & Televisi',
  'Film Production & Cinematography',
  'Seni',
  'Penulisan skenario dramatis, teknik directing sutradara, tata kamera sinematik, tata artistik, dan penyuntingan video pascaproduksi berstandar industri.',
  'Dramatic screenwriting, directing techniques, cinematic lighting & camerawork, art direction, and post-production video editing.',
  '["Penulisan Naskah Film","Tata Kamera & Tata Cahaya Sinematik","Penyutradaraan Fiksi & Dokumenter","Editing Video & Color Grading","Tata Suara & Sound Design"]'::jsonb,
  '["Screenwriting & Narrative Design","Cinematography & Lighting","Directing Fiction & Documentary","Video Editing & Color Grading","Sound Design & Audio Mixing"]'::jsonb,
  'S1',
  4,
  'High',
  'AES',
  '["ENFP","INFP","ENTP","ISFP"]'::jsonb,
  '["video-editor","motion-graphic-designer"]'::jsonb
),
(
  'm-fotografi-komersial',
  'fotografi-komersial',
  '50.0605',
  'Fotografi & Seni Media Digital',
  'Commercial Photography & Digital Media Arts',
  'Seni',
  'Penguasaan pencahayaan studio, fotografi produk komersial, editorial fesyen, jurnalisme foto, dan teknik olah digital retus foto profesional.',
  'Mastery of studio lighting, commercial product photography, fashion editorials, photojournalism, and high-end digital retouching techniques.',
  '["Teknik Tata Cahaya Studio","Fotografi Produk & Makanan Komersial","Fotografi Mode & Potret","Digital Retouching & Manajemen Warna","Bisnis & Hak Cipta Fotografi"]'::jsonb,
  '["Studio Lighting Techniques","Commercial Product & Food Photography","Fashion & Portrait Photography","Digital Retouching & Color Management","Photography Business & Copyright"]'::jsonb,
  'S1 / D4',
  4,
  'Medium',
  'AER',
  '["ISFP","ESFP","ISTP","INFP"]'::jsonb,
  '["commercial-photographer","graphic-designer"]'::jsonb
),
(
  'm-desain-mode',
  'desain-mode',
  '50.0407',
  'Desain Mode & Bisnis Busana',
  'Fashion Design & Apparel Merchandising',
  'Seni',
  'Perancangan koleksi busana tematik, pembuatan pola presisi (pattern making), teknologi tekstil, draping haute couture, dan bisnis fesyen berkelanjutan.',
  'Thematic apparel collection design, pattern making precision, textile technology, haute couture draping, and sustainable fashion entrepreneurship.',
  '["Ilustrasi Mode & Konsep Koleksi","Pembuatan Pola Datar & Draping","Teknologi Tekstil & Bahan Busana","Konstruksi Garmen & Jahit Tingkat Lanjut","Manajemen Bisnis & Ritel Mode"]'::jsonb,
  '["Fashion Illustration & Collection Concepts","Flat Pattern Drafting & Draping","Textile Science & Fabrics","Advanced Garment Construction","Fashion Merchandising & Retail"]'::jsonb,
  'S1 / D4',
  4,
  'High',
  'AES',
  '["ISFP","ESFP","ENFP","INFP"]'::jsonb,
  '["fashion-designer"]'::jsonb
),
(
  'm-bioteknologi',
  'bioteknologi',
  '26.1201',
  'Bioteknologi Molekuler & Rekayasa Hayati',
  'Molecular Biotechnology & Bioengineering',
  'Saintek',
  'Pemanfaatan mikroorganisme, rekayasa genetika DNA rekombinan, kultur sel, dan bioinformatika untuk obat-obatan baru serta ketahanan pangan.',
  'Utilization of microorganisms, recombinant DNA genetic engineering, cell cultures, and bioinformatics for novel pharmaceuticals and food security.',
  '["Biologi Sel & Molekuler","Rekayasa Genetika & Kloning","Bioinformatika & Genomika","Teknologi Fermentasi Industri","Imunobiologi Terapan"]'::jsonb,
  '["Cell & Molecular Biology","Genetic Engineering & Cloning","Bioinformatics & Genomics","Industrial Fermentation Technology","Applied Immunobiology"]'::jsonb,
  'S1',
  4,
  'High',
  'IRC',
  '["INTP","INTJ","INFJ","ISTJ"]'::jsonb,
  '["research-scientist","medical-lab-technologist"]'::jsonb
),
(
  'm-matematika-aktuaria',
  'matematika-aktuaria',
  '27.0101',
  'Matematika Terapan & Sains Aktuaria',
  'Applied Mathematics & Actuarial Science',
  'Saintek',
  'Pemodelan kalkulus diferensial, probabilitas stokastik, teori resiko finansial asuransi, dan kalkulasi premi dana pensiun berakurasi tinggi.',
  'Differential calculus modeling, stochastic probability, actuarial financial risk theory, and high-accuracy pension & insurance calculations.',
  '["Matematika Keuangan","Teori Probabilitas & Proses Stokastik","Matematika Aktuaria & Premi Asuransi","Pemodelan Matematika Komputasi","Analisis Regresi Deret Waktu"]'::jsonb,
  '["Financial Mathematics","Probability Theory & Stochastic Processes","Actuarial Mathematics & Premiums","Computational Mathematical Modeling","Time Series Regression Analysis"]'::jsonb,
  'S1',
  4,
  'High',
  'ICE',
  '["INTJ","INTP","ISTJ","ENTJ"]'::jsonb,
  '["financial-analyst","data-scientist"]'::jsonb
),
(
  'm-fisika-terapan',
  'fisika-terapan',
  '40.0801',
  'Fisika Terapan & Instrumentasi Sensor',
  'Applied Physics & Sensor Instrumentation',
  'Saintek',
  'Penyelidikan mekanika kuantum, optika laser modern, fisika zat padat (semikonduktor), dan perancangan sensor cerdas berpresisi tinggi.',
  'Investigation of quantum mechanics, modern laser optics, solid-state semiconductor physics, and high-precision smart sensor instrumentation.',
  '["Mekanika Kuantum Terapan","Fisika Semikonduktor & Nanomaterial","Optoelektronika & Laser","Sistem Akuisisi Data Sensor","Fisika Komputasi"]'::jsonb,
  '["Applied Quantum Mechanics","Semiconductor & Nanomaterial Physics","Optoelectronics & Lasers","Sensor Data Acquisition Systems","Computational Physics"]'::jsonb,
  'S1',
  4,
  'High',
  'IRE',
  '["INTP","INTJ","ISTP","ISTJ"]'::jsonb,
  '["research-scientist","radiologic-technologist"]'::jsonb
),
(
  'm-kimia-industri',
  'kimia-industri',
  '40.0501',
  'Ilmu Kimia Murni & Material Maju',
  'Pure Chemistry & Advanced Materials',
  'Saintek',
  'Eksplorasi ikatan molekuler kimia organik dan anorganik, spektroskopi analitik, sintesis polimer maju, dan nanoteknologi berkelanjutan.',
  'Exploration of organic and inorganic molecular bonding, analytical spectroscopy, advanced polymer synthesis, and sustainable nanotechnology.',
  '["Kimia Organik & Anorganik Sintesis","Kimia Analitik Spektroskopi (NMR/FTIR)","Termodinamika Kimia Fisik","Kimia Polimer & Material Komposit","Kimia Hijau (Green Chemistry)"]'::jsonb,
  '["Synthetic Organic & Inorganic Chemistry","Spectroscopic Analytical Chemistry","Physical Chemical Thermodynamics","Polymer Chemistry & Composites","Green Chemistry"]'::jsonb,
  'S1',
  4,
  'High',
  'IRC',
  '["INTP","INTJ","ISTJ","INFJ"]'::jsonb,
  '["research-scientist","medical-lab-technologist"]'::jsonb
),
(
  'm-teknik-kimia',
  'teknik-kimia',
  '14.0701',
  'Teknik Kimia & Perancangan Pabrik',
  'Chemical & Process Engineering',
  'Saintek',
  'Transformasi bahan mentah menjadi produk bernilai tinggi secara ekonomis melalui rekayasa reaksi kimia, pemisahan distilasi, dan perancangan reaktor industri.',
  'Converting raw materials into valuable commercial goods through chemical reaction engineering, distillation separation, and industrial reactor design.',
  '["Neraca Massa & Energi","Operasi Teknik Kimia (Distilasi/Filtrasi)","Kinetika Reaksi & Perancangan Reaktor","Perancangan Pabrik Kimia","Keselamatan Proses Pabrik (K3)"]'::jsonb,
  '["Mass & Energy Balances","Chemical Unit Operations","Reaction Kinetics & Reactor Design","Chemical Plant Design","Process Plant Safety"]'::jsonb,
  'S1',
  4,
  'High',
  'RIE',
  '["INTJ","ISTJ","ENTJ","INTP"]'::jsonb,
  '["research-scientist","mechanical-engineer"]'::jsonb
),
(
  'm-teknik-telekomunikasi',
  'teknik-telekomunikasi',
  '14.1004',
  'Teknik Telekomunikasi & Jaringan Nirkabel',
  'Telecommunications & Wireless Engineering',
  'Saintek',
  'Mempelajari propagasi gelombang elektromagnetik, arsitektur seluler 5G/6G, transmisi fiber optik pita lebar, dan infrastruktur satelit komunikasi.',
  'Studies electromagnetic wave propagation, 5G/6G cellular architecture, broadband optical fiber transmission, and satellite communications.',
  '["Propagasi Gelombang Mikro & Antena","Sistem Komunikasi Nirkabel 5G","Komunikasi Serat Optik","Jaringan Protokol IP Lanjutan","Pengolahan Sinyal Digital (DSP)"]'::jsonb,
  '["Microwave Propagation & Antennas","5G Wireless Communications","Optical Fiber Communications","Advanced IP Network Protocols","Digital Signal Processing (DSP)"]'::jsonb,
  'S1',
  4,
  'High',
  'RIE',
  '["INTJ","INTP","ISTP","ISTJ"]'::jsonb,
  '["electrical-engineer","devops-engineer"]'::jsonb
),
(
  'm-teknik-penerbangan',
  'teknik-penerbangan',
  '14.0201',
  'Teknik Dirgantara & Penerbangan (Aerospace)',
  'Aerospace & Aeronautical Engineering',
  'Saintek',
  'Perancangan aerodinamika pesawat terbang, struktur bodi pesawat tahan beban g, sistem propulsi jet turbofan, dan instrumen avionik modern.',
  'Design of aircraft aerodynamics, g-force resistant fuselage structures, turbofan jet propulsion, and modern avionics navigation instruments.',
  '["Aerodinamika Kecepatan Tinggi (Supersonik)","Struktur Pesawat Terbang & Komposit","Mekanika Terbang & Dinamika Kendali","Propulsi Jet Pesawat","Avionik & Navigasi Penerbangan"]'::jsonb,
  '["High-Speed Aerodynamics","Aircraft Structures & Composites","Flight Mechanics & Control Dynamics","Aircraft Jet Propulsion","Avionics & Flight Navigation"]'::jsonb,
  'S1',
  4,
  'High',
  'RIE',
  '["INTJ","INTP","ISTP","ENTJ"]'::jsonb,
  '["mechanical-engineer","research-scientist"]'::jsonb
),
(
  'm-teknik-geologi',
  'teknik-geologi',
  '14.3901',
  'Teknik Geologi & Eksplorasi Sumber Daya',
  'Geological Engineering & Exploration',
  'Saintek',
  'Pemetaan struktur batuan bumi, eksplorasi cebakan mineral dan energi panas bumi, mitigasi bencana vulkanologi/gempa bumi, dan hidrogeologi tanah.',
  'Mapping subterranean rock structures, exploring geothermal energy and mineral deposits, mitigations for seismic hazards, and soil hydrogeology.',
  '["Petrologi & Mineralogi","Geologi Struktur & Tektonik","Eksplorasi Geokimia & Geofisika","Geologi Rekayasa & Mitigasi Bencana","Hidrogeologi & Air Tanah"]'::jsonb,
  '["Petrology & Mineralogy","Structural Geology & Tectonics","Geochemical & Geophysical Exploration","Engineering Geology & Hazard Mitigation","Hydrogeology & Groundwater"]'::jsonb,
  'S1',
  4,
  'High',
  'RIC',
  '["ISTP","ISTJ","INTJ","INTP"]'::jsonb,
  '["civil-engineer","research-scientist"]'::jsonb
),
(
  'm-teknologi-blockchain',
  'teknologi-blockchain',
  '11.0104',
  'Teknologi Blockchain & Komputasi Terdistribusi',
  'Blockchain Technology & Distributed Systems',
  'Saintek',
  'Mempelajari protokol konsensus terdistribusi, perancangan smart contract aman, arsitektur DeFi, Web3, dan kriptografi zero-knowledge proof.',
  'Studies distributed consensus protocols, secure smart contract engineering, DeFi frameworks, Web3 architectures, and zero-knowledge cryptography.',
  '["Algoritma Konsensus Terdistribusi","Pemrograman Smart Contract (Solidity/Rust)","Kriptografi Terapan & ZK-Proofs","Audit Keamanan Web3 & Smart Contracts","Arsitektur Tokenomika"]'::jsonb,
  '["Distributed Consensus Algorithms","Smart Contract Programming (Solidity/Rust)","Applied Cryptography & ZK-Proofs","Web3 Security Auditing","Tokenomics Architecture"]'::jsonb,
  'S1',
  4,
  'High',
  'IRC',
  '["INTJ","INTP","ENTP","ISTP"]'::jsonb,
  '["blockchain-developer","software-engineer","cybersecurity-specialist"]'::jsonb
),
(
  'm-rekayasa-kecerdasan-buatan',
  'rekayasa-kecerdasan-buatan',
  '11.0102',
  'Rekayasa Kecerdasan Buatan (Artificial Intelligence)',
  'Artificial Intelligence Systems Engineering',
  'Saintek',
  'Fokus spesifik pada arsitektur Deep Learning (Transformer), Large Language Models (LLM), Computer Vision, Pemrosesan Bahasa Alami (NLP), dan AI Agent.',
  'Dedicated focus on Deep Learning architectures (Transformers), Large Language Models (LLMs), Computer Vision, NLP, and Autonomous AI Agents.',
  '["Jaringan Saraf Tiruan Lanjutan","Natural Language Processing & LLMs","Computer Vision & Generative AI","Optimasi Hardware AI (CUDA/GPU)","Etika & Keamanan AI"]'::jsonb,
  '["Advanced Neural Networks","Natural Language Processing & LLMs","Computer Vision & Generative AI","AI Hardware Optimization (CUDA/GPU)","AI Ethics & Safety"]'::jsonb,
  'S1',
  4,
  'High',
  'IRC',
  '["INTJ","INTP","ENTP","ENTJ"]'::jsonb,
  '["ai-machine-learning-engineer","data-scientist","software-engineer"]'::jsonb
),
(
  'm-kesehatan-masyarakat',
  'kesehatan-masyarakat',
  '51.2201',
  'Kesehatan Masyarakat & Epidemiologi',
  'Public Health & Global Epidemiology',
  'Saintek',
  'Surveilans penyakit menular dan kronis, analisis biostatistika populasi, promosi gaya hidup sehat, dan perumusan kebijakan kesehatan preventif.',
  'Surveillance of infectious and chronic diseases, biostatistical population analysis, healthy lifestyle promotion, and preventive healthcare policies.',
  '["Epidemiologi Penyakit Menular & Kronis","Biostatistika Kesehatan Masyarakat","Kebijakan & Manajemen Kesehatan","Kesehatan Lingkungan & Kerja","Promosi Kesehatan & Perilaku"]'::jsonb,
  '["Epidemiology of Infectious & Chronic Diseases","Public Health Biostatistics","Health Policy & Management","Environmental & Occupational Health","Health Promotion & Behavior"]'::jsonb,
  'S1',
  4,
  'High',
  'SIC',
  '["ENFJ","INFJ","ESFJ","ISTJ"]'::jsonb,
  '["perawat","research-scientist"]'::jsonb
),
(
  'm-kebidanan',
  'kebidanan',
  '51.3807',
  'Kebidanan & Kesehatan Reproduksi',
  'Midwifery & Maternal Health Sciences',
  'Saintek',
  'Pelayanan asuhan kebidanan pada masa prakonsepsi, kehamilan, persalinan normal, nifas, bayi baru lahir, serta pelayanan kontrasepsi keluarga berencana.',
  'Midwifery care across preconception, antenatal stages, normal deliveries, postpartum recovery, neonatal care, and family planning contraception.',
  '["Asuhan Kebidanan Kehamilan Normal","Asuhan Persalinan & Bayi Baru Lahir","Kegawatdaruratan Maternal & Neonatal","Kesehatan Reproduksi & KB","Komunikasi Terapeutik Kebidanan"]'::jsonb,
  '["Antenatal Midwifery Care","Labor & Neonatal Delivery Care","Maternal & Neonatal Emergencies","Reproductive Health & Family Planning","Therapeutic Midwifery Communication"]'::jsonb,
  'D4 / S1 + Profesi',
  5,
  'High',
  'SIR',
  '["ISFJ","ESFJ","INFJ","ENFJ"]'::jsonb,
  '["nurse-midwife","perawat"]'::jsonb
),
(
  'm-kedokteran-hewan',
  'kedokteran-hewan',
  '51.2501',
  'Kedokteran Hewan & Kesehatan Ternak',
  'Veterinary Medicine & Animal Health',
  'Saintek',
  'Diagnosa dan penanganan medis satwa peliharaan, satwa liar, dan ternak, pencegahan penyakit zoonosis yang menular ke manusia, dan keamanan pangan asal hewan.',
  'Medical diagnosis and surgical treatment of companion pets, wildlife, and livestock, prevention of zoonotic diseases, and animal food safety.',
  '["Anatomi & Fisiologi Hewan Komparatif","Patologi & Parasitologi Veteriner","Farmakologi & Terapi Veteriner","Ilmu Bedah Satwa Kecil & Besar","Kesehatan Masyarakat Veteriner (Zoonosis)"]'::jsonb,
  '["Comparative Animal Anatomy & Physiology","Veterinary Pathology & Parasitology","Veterinary Pharmacology & Therapy","Small & Large Animal Surgery","Veterinary Public Health (Zoonoses)"]'::jsonb,
  'S1 + Profesi',
  5,
  'High',
  'IRS',
  '["ISFJ","ISTJ","INFJ","ISTP"]'::jsonb,
  '["dokter-umum","research-scientist"]'::jsonb
),
(
  'm-ilmu-ekonomi',
  'ilmu-ekonomi',
  '45.0601',
  'Ilmu Ekonomi & Ekonometrika Terapan',
  'Economics & Applied Econometrics',
  'Soshum',
  'Analisis perilaku pasar mikroekonomi, kebijakan moneter dan fiskal makroekonomi, teori pertumbuhan ekonomi, dan pemodelan statistik ekonometrika.',
  'Analysis of microeconomic market behaviors, macroeconomic monetary and fiscal policies, growth theories, and econometric statistical modeling.',
  '["Mikroekonomi & Makroekonomi Menengah","Ekonometrika Terapan & Regresi","Ekonomi Moneter & Kebijakan Fiskal","Ekonomi Pembangunan & Perdagangan Internasional","Ekonomi Publik & Regulasi"]'::jsonb,
  '["Intermediate Micro & Macroeconomics","Applied Econometrics & Regression","Monetary Economics & Fiscal Policy","Development & International Trade Economics","Public Economics & Regulation"]'::jsonb,
  'S1',
  4,
  'High',
  'ICE',
  '["INTJ","ENTJ","INTP","ESTJ"]'::jsonb,
  '["financial-analyst","research-scientist"]'::jsonb
),
(
  'm-bisnis-internasional',
  'bisnis-internasional',
  '52.1101',
  'Bisnis Internasional & Ekspor-Impor',
  'International Business & Global Trade',
  'Soshum',
  'Strategi penetrasi pasar luar negeri, kepatuhan bea cukai ekspor-impor, manajemen risiko nilai tukar valas, dan etika negosiasi multikultural.',
  'Foreign market entry strategies, customs compliance, foreign exchange risk hedging, and multicultural business negotiation frameworks.',
  '["Strategi Perdagangan & Bisnis Global","Hukum & Prosedur Ekspor Impor","Manajemen Keuangan Multinasional","Pemasaran Global Lintas Budaya","Negosiasi Bisnis Internasional"]'::jsonb,
  '["Global Business Strategy & Trade","Export-Import Law & Procedures","Multinational Financial Management","Cross-Cultural Global Marketing","International Business Negotiation"]'::jsonb,
  'S1',
  4,
  'High',
  'ECS',
  '["ENTJ","ENTP","ESTJ","ENFJ"]'::jsonb,
  '["business-development-manager","brand-manager"]'::jsonb
),
(
  'm-manajemen-logistik',
  'manajemen-logistik',
  '52.0203',
  'Manajemen Logistik & Rantai Pasok Global',
  'Logistics & Global Supply Chain Management',
  'Soshum',
  'Manajemen pergudangan otomatis, jaringan rute distribusi transportasi darat-laut-udara, pengelolaan inventaris just-in-time, dan logistik e-commerce.',
  'Automated warehouse management, multi-modal transport route planning, just-in-time inventory control, and omni-channel e-commerce fulfillment.',
  '["Manajemen Pengadaan (Procurement)","Sistem Pergudangan & Inventaris","Manajemen Transportasi & Distribusi","Supply Chain Analytics","Logistik Pelabuhan & Multimoda"]'::jsonb,
  '["Procurement Management","Warehousing & Inventory Systems","Transportation & Distribution Management","Supply Chain Analytics","Port & Multimodal Logistics"]'::jsonb,
  'S1 / D4',
  4,
  'High',
  'ECS',
  '["ESTJ","ISTJ","ENTJ","INTJ"]'::jsonb,
  '["business-development-manager","product-manager"]'::jsonb
),
(
  'm-ilmu-perpustakaan',
  'ilmu-perpustakaan',
  '25.0101',
  'Ilmu Informasi & Manajemen Arsip Digital',
  'Library & Digital Archival Information Science',
  'Soshum',
  'Klasifikasi taksonomi metadata (DDC/LCC), preservasi arsip dokumen digital, manajemen repositori institusi, dan literasi pencarian informasi ilmiah.',
  'Metadata taxonomy classification (DDC/LCC), preservation of digital archives, institutional repositories, and advanced scholarly information retrieval.',
  '["Organisasi Informasi & Katalogisasi","Preservasi & Konservasi Dokumen Digital","Sistem Temu Kembali Informasi (Search)","Manajemen Repositori & Basis Data Terbuka","Literasi Informasi & Hak Cipta"]'::jsonb,
  '["Information Organization & Cataloging","Digital Document Preservation","Information Retrieval Systems","Repository & Open Access Management","Information Literacy & Copyright"]'::jsonb,
  'S1',
  4,
  'Medium',
  'CSI',
  '["ISTJ","INFJ","INTJ","ISFJ"]'::jsonb,
  '["digital-archivist-librarian"]'::jsonb
),
(
  'm-sastra-inggris',
  'sastra-inggris',
  '23.0101',
  'Sastra Inggris & Komunikasi Global',
  'English Literature & Global Linguistics',
  'Soshum',
  'Analisis wacana linguistik kritis, teori sastra komparatif, penulisan narasi kreatif berbahasa Inggris, penerjemahan profesional, dan lokalisasi konten.',
  'Critical linguistic discourse analysis, comparative literary theory, creative narrative writing, professional translation, and content localization.',
  '["Linguistik Struktural & Fonologi","Analisis Wacana Kritis (Discourse)","Kritik Sastra & Kajian Budaya","Penerjemahan Teks & Subtitling","Penulisan Kreatif & Copywriting"]'::jsonb,
  '["Structural Linguistics & Phonology","Critical Discourse Analysis","Literary Criticism & Cultural Studies","Professional Translation & Subtitling","Creative Writing & Copywriting"]'::jsonb,
  'S1',
  4,
  'Medium',
  'ASI',
  '["INFP","INFJ","ENFP","ENTP"]'::jsonb,
  '["copywriter","social-media-manager"]'::jsonb
),
(
  'm-seni-rupa-murni',
  'seni-rupa-murni',
  '50.0701',
  'Seni Rupa Murni & Kurasi Pameran',
  'Fine Arts, Painting & Curatorial Studies',
  'Seni',
  'Eksplorasi artistik seni lukis, seni patung 3D, seni instalasi konseptual, estetika seni kontemporer, dan tata kelola kurasi galeri seni.',
  'Artistic explorations in painting, sculpture, conceptual installations, contemporary art aesthetics, and art gallery curatorial management.',
  '["Studio Seni Lukis & Gambar Sketsa","Seni Patung & Konstruksi 3D","Sejarah & Filsafat Estetika Seni","Kritik Seni & Manajemen Pameran (Kurasi)","Seni Instalasi & Intermedia"]'::jsonb,
  '["Painting Studio & Drawing","Sculpture & 3D Construction","History & Aesthetics Philosophy","Art Criticism & Exhibition Curating","Installation Art & Intermedia"]'::jsonb,
  'S1',
  4,
  'Medium',
  'AES',
  '["ISFP","INFP","INTP","INFJ"]'::jsonb,
  '["graphic-designer","commercial-photographer"]'::jsonb
),
(
  'm-seni-musik',
  'seni-musik',
  '50.0901',
  'Seni Musik & Rekayasa Audio',
  'Music Performance & Audio Engineering',
  'Seni',
  'Teori harmoni musik barat, aransemen orkestrasi, penguasaan instrumen virtuoso, perekaman multi-track DAW, dan tata mixing audio profesional.',
  'Western harmony theory, orchestral arrangements, instrument virtuosity, multi-track DAW recording, and professional audio mixing & mastering.',
  '["Harmoni Musik & Solfeggio","Komposisi & Aransemen Musik","Produksi Audio Digital (DAW)","Teknik Mixing & Mastering Audio","Manajemen Bisnis Musik & Hak Cipta"]'::jsonb,
  '["Harmony Theory & Solfege","Music Composition & Arrangement","Digital Audio Production (DAW)","Audio Mixing & Mastering","Music Business & Royalties"]'::jsonb,
  'S1',
  4,
  'Medium',
  'AES',
  '["ISFP","INFP","ESFP","ENTP"]'::jsonb,
  '["video-editor","animator-3d-artist"]'::jsonb
),
(
  'm-desain-game-interaksi',
  'desain-game-interaksi',
  '50.0411',
  'Desain Game & Interaksi Pengguna (Game UI/UX)',
  'Game Design & Interactive Experience',
  'Seni',
  'Penciptaan game loop yang memikat, desain level interaktif, antarmuka game diegetik (UI/UX), penulisan narasi lore, dan psikologi keterikatan pemain.',
  'Crafting engaging core game loops, level design, diegetic gaming UI/UX, immersive narrative lore, and player engagement psychology.',
  '["Prinsip Desain Game & Game Loop","Desain Level & Puzzle Interaktif","Game UI/UX & Antarmuka Spasial","Storytelling & Penulisan Lore Game","Prototyping Game Cepat"]'::jsonb,
  '["Game Design & Core Loops","Interactive Level & Puzzle Design","Spatial Game UI/UX","Game Lore Storytelling","Rapid Game Prototyping"]'::jsonb,
  'S1 / D4',
  4,
  'High',
  'AIE',
  '["INTP","INTJ","ENTP","ENFP"]'::jsonb,
  '["game-designer","ui-ux-designer","animator-3d-artist"]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  slug = EXCLUDED.slug,
  cip_code = EXCLUDED.cip_code,
  name_id = EXCLUDED.name_id,
  name_en = EXCLUDED.name_en,
  category = EXCLUDED.category,
  description_id = EXCLUDED.description_id,
  description_en = EXCLUDED.description_en,
  typical_subjects_id = EXCLUDED.typical_subjects_id,
  typical_subjects_en = EXCLUDED.typical_subjects_en,
  min_education_level = EXCLUDED.min_education_level,
  avg_duration_years = EXCLUDED.avg_duration_years,
  career_prospect = EXCLUDED.career_prospect,
  riasec_code = EXCLUDED.riasec_code,
  matched_mbti = EXCLUDED.matched_mbti,
  matched_professions_slugs = EXCLUDED.matched_professions_slugs,
  updated_at = timezone('utc'::text, now());
